/**
 * 设置注册表 —— 全量设置项索引（供设置搜索使用）。
 * 对齐 iOS Settings 搜索：输入关键词 → 按分类分组显示匹配项 → 点击跳转对应页面。
 */
export interface SettingItem {
  key: string;
  /** 显示名称 */
  label: string;
  /** 搜索关键词（含同义词） */
  keywords: string[];
  /** SF Symbol 图标 */
  icon: string;
  /** 目标页面路由 */
  page: string;
  /** 所属分类标题 */
  category: string;
  /** 分类图标颜色 */
  color: string;
}

export const SETTINGS_REGISTRY: SettingItem[] = [
  // ===== 推荐设置 =====
  { key: 'appRcmd', label: '使用App端推荐', keywords: ['推荐', 'app', '来源'], icon: 'app.badge', page: '/settings/recommend', category: '推荐设置', color: '#FF9500' },
  { key: 'enableSaveLastData', label: '保留推荐刷新', keywords: ['刷新', '保留', '推荐'], icon: 'arrow.clockwise', page: '/settings/recommend', category: '推荐设置', color: '#FF9500' },
  { key: 'savedRcmdTip', label: '显示上次看到位置', keywords: ['位置', '提示', '上次'], icon: 'location', page: '/settings/recommend', category: '推荐设置', color: '#FF9500' },
  { key: 'showHotRcmd', label: '显示热门推荐', keywords: ['热门', '推荐', '每周必看'], icon: 'flame.fill', page: '/settings/recommend', category: '推荐设置', color: '#FF9500' },
  { key: 'minLikeRatio', label: '点赞率过滤', keywords: ['过滤', '点赞', '比率'], icon: 'hand.thumbsup', page: '/settings/recommend', category: '推荐设置', color: '#FF9500' },
  { key: 'minDuration', label: '视频时长过滤', keywords: ['过滤', '时长', '短视频'], icon: 'timer', page: '/settings/recommend', category: '推荐设置', color: '#FF9500' },
  { key: 'minPlay', label: '播放量过滤', keywords: ['过滤', '播放量', '播放数'], icon: 'play.circle', page: '/settings/recommend', category: '推荐设置', color: '#FF9500' },
  { key: 'exemptFilterForFollowed', label: '已关注UP豁免过滤', keywords: ['关注', '豁免', '过滤'], icon: 'heart', page: '/settings/recommend', category: '推荐设置', color: '#FF9500' },
  { key: 'applyFilterToRelated', label: '过滤器应用于相关视频', keywords: ['过滤', '相关视频', '详情页'], icon: 'square.stack.3d.up', page: '/settings/recommend', category: '推荐设置', color: '#FF9500' },
  { key: 'banWordForRecommend', label: '标题关键词过滤', keywords: ['屏蔽词', '关键词', '标题', '过滤'], icon: 'text.badge.xmark', page: '/settings/recommend', category: '推荐设置', color: '#FF9500' },
  { key: 'banWordForZone', label: '视频分区关键词过滤', keywords: ['分区', '关键词', '过滤', '屏蔽'], icon: 'square.grid.2x2', page: '/settings/recommend', category: '推荐设置', color: '#FF9500' },

  // ===== 视频/画质 =====
  { key: 'enableHA', label: '开启硬解', keywords: ['硬解', '解码', '硬件加速'], icon: 'bolt', page: '/settings/video', category: '视频 / 画质', color: '#007AFF' },
  { key: 'enableSuperResolution', label: '超分辨率', keywords: ['超分', '超分辨率', '画质增强', '清晰度'], icon: 'arrow.up.left.and.arrow.down.right', page: '/settings/video', category: '视频 / 画质', color: '#007AFF' },
  { key: 'enableFrameInterpolation', label: '补帧', keywords: ['补帧', '插帧', '帧率', '画质增强'], icon: 'film.stack', page: '/settings/video', category: '视频 / 画质', color: '#007AFF' },
  { key: 'enableSdrToHdr', label: 'SDR→HDR 映射', keywords: ['SDR', 'HDR', '映射', '色域', '画质增强'], icon: 'sun.max.trianglebadge.exclamationmark', page: '/settings/video', category: '视频 / 画质', color: '#007AFF' },
  { key: 'p1080', label: '免登录1080P', keywords: ['1080', '免登录', '画质'], icon: 'lock.open', page: '/settings/video', category: '视频 / 画质', color: '#007AFF' },
  { key: 'preferCodec', label: '首选解码格式', keywords: ['解码', 'H264', 'H265', 'HEVC', 'AV1', '编码'], icon: 'film.stack', page: '/settings/video', category: '视频 / 画质', color: '#007AFF' },
  { key: 'defaultQuality', label: '默认画质', keywords: ['画质', '清晰度', '4K', '1080P', '720P'], icon: 'film', page: '/settings/video', category: '视频 / 画质', color: '#007AFF' },
  { key: 'cellularQuality', label: '蜂窝网络画质', keywords: ['流量', '蜂窝', '画质', '移动网络'], icon: 'antenna.radiowaves.left.and.right', page: '/settings/video', category: '视频 / 画质', color: '#007AFF' },
  { key: 'defaultAudioQa', label: '默认音质', keywords: ['音质', '音频', ' Hi-Res', '杜比'], icon: 'music.note', page: '/settings/video', category: '视频 / 画质', color: '#007AFF' },
  { key: 'cellularAudioQa', label: '蜂窝网络音质', keywords: ['流量', '蜂窝', '音质'], icon: 'music.note.list', page: '/settings/video', category: '视频 / 画质', color: '#007AFF' },
  { key: 'disableAudioCDN', label: '音频不跟随CDN', keywords: ['音频', 'CDN', '无声'], icon: 'music.quarternote.3', page: '/settings/video', category: '视频 / 画质', color: '#007AFF' },
  { key: 'liveQuality', label: '直播默认画质', keywords: ['直播', '画质', '原画', '蓝光'], icon: 'dot.radiowaves.left.and.right', page: '/settings/video', category: '视频 / 画质', color: '#007AFF' },
  { key: 'cellularLiveQuality', label: '蜂窝直播画质', keywords: ['直播', '流量', '画质'], icon: 'cellularbars', page: '/settings/video', category: '视频 / 画质', color: '#007AFF' },
  { key: 'cdnService', label: 'CDN设置', keywords: ['CDN', '加速', '阿里', '腾讯', '播放源'], icon: 'server.rack', page: '/settings/video', category: '视频 / 画质', color: '#007AFF' },
  { key: 'liveCdnUrl', label: '直播CDN设置', keywords: ['直播', 'CDN', 'host'], icon: 'cloud', page: '/settings/video', category: '视频 / 画质', color: '#007AFF' },
  { key: 'cdnSpeedTest', label: 'CDN测速', keywords: ['CDN', '测速', '速度'], icon: 'speedometer', page: '/settings/video', category: '视频 / 画质', color: '#007AFF' },
  { key: 'bufferSize', label: '缓冲大小', keywords: ['缓冲', '内存', '卡顿'], icon: 'internaldrive', page: '/settings/video', category: '视频 / 画质', color: '#007AFF' },
  { key: 'bufferSec', label: '缓冲时长', keywords: ['缓冲', '时长', '秒'], icon: 'clock', page: '/settings/video', category: '视频 / 画质', color: '#007AFF' },

  // ===== 播放设置 =====
  { key: 'autoPlay', label: '自动播放', keywords: ['播放', '自动', '进入播放'], icon: 'play.circle', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'playOnWifi', label: '仅WiFi下播放', keywords: ['WiFi', '流量', '播放限制'], icon: 'wifi', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'continuePlayInBackground', label: '后台播放', keywords: ['后台', '播放', '锁屏', '息屏'], icon: 'moon.circle', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'playRepeat', label: '播放顺序', keywords: ['循环', '顺序', '单曲', '随机'], icon: 'repeat', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'enableOnlineTotal', label: '显示观看人数', keywords: ['在线', '人数', '在看'], icon: 'person.2', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'enableHeartbeat', label: '上报播放进度', keywords: ['历史', '进度', '续播', '记录'], icon: 'icloud.and.arrow.up', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'showSeekPreview', label: '滑动跳转预览缩略图', keywords: ['预览', '缩略图', '拖动', '进度条'], icon: 'film.stack', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'enableBackgroundPlay', label: '后台音频服务', keywords: ['后台', '音频', '服务'], icon: 'speaker.wave.2', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'enableLongShowControl', label: '延长控件显示时间', keywords: ['控件', '显示时间', '30秒'], icon: 'timer', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'tempPlayerConf', label: '播放器设置仅对当前生效', keywords: ['临时', '当前', '重置'], icon: 'arrow.counterclockwise', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'defaultPlaySpeed', label: '默认播放倍速', keywords: ['倍速', '速度', '播放速度'], icon: 'gauge.with.dots.needle.67percent', page: '/settings/play_speed', category: '播放设置', color: '#34C759' },
  { key: 'enableAutoLongPressSpeed', label: '长按倍速播放', keywords: ['长按', '倍速', '加速'], icon: 'hand.point.up.left', page: '/settings/play_speed', category: '播放设置', color: '#34C759' },
  { key: 'longPressSpeedDefault', label: '长按倍速值', keywords: ['长按', '倍速', '3x', '5x'], icon: 'gauge.with.dots.needle.100percent', page: '/settings/play_speed', category: '播放设置', color: '#34C759' },
  { key: 'playSpeedSet', label: '倍速设置', keywords: ['倍速', '速度', '自定义', '列表'], icon: 'speedometer', page: '/settings/play_speed', category: '播放设置', color: '#34C759' },
  { key: 'enableQuickDouble', label: '双击快退/快进', keywords: ['双击', '快进', '快退'], icon: 'hand.tap', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'fastForBackwardDuration', label: '双击快进时长', keywords: ['双击', '时长', '5秒', '10秒', '15秒'], icon: 'forward', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'enableSlideVolumeBrightness', label: '滑动调节亮度/音量', keywords: ['亮度', '音量', '滑动', '手势'], icon: 'sun.max', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'enableSlideFS', label: '中间滑动进入/退出全屏', keywords: ['全屏', '滑动', '手势'], icon: 'arrow.up.and.down', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'sliderDuration', label: '滑动快进时长', keywords: ['滑动', '快进', '时长'], icon: 'hand.draw', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'enableShrinkVideoSize', label: '双指缩小视频', keywords: ['缩放', '双指', '捏合', '小窗'], icon: 'arrow.down.right.and.arrow.up.left.circle', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'useRelativeSlide', label: '滑动快进使用相对时长', keywords: ['相对', '滑动', '百分比'], icon: 'arrow.left.and.right', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'playerVolume', label: '播放器音量', keywords: ['音量', '大小', '声音'], icon: 'speaker.wave.3', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'enableVerticalExpand', label: '竖屏扩大展示', keywords: ['竖屏', '扩大', '比例', '1:1'], icon: 'arrow.up.backward.and.arrow.down.forward', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'enableAutoEnter', label: '自动全屏', keywords: ['全屏', '自动', '进入'], icon: 'arrow.up.left.and.arrow.down.right', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'enableAutoExit', label: '自动退出全屏', keywords: ['全屏', '退出', '结束'], icon: 'arrow.down.right.and.arrow.up.left', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'autoRotate', label: '重力感应自动旋转', keywords: ['旋转', '重力', '陀螺仪', '横屏'], icon: 'gyroscope', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'fullScreenGestureReverse', label: '全屏手势反向', keywords: ['手势', '反向', '全屏'], icon: 'arrow.triangle.swap', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'fullScreenMode', label: '默认全屏方向', keywords: ['全屏', '方向', '横向', '竖向'], icon: 'rotate.right', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'showFSActionItem', label: '全屏显示操作按钮', keywords: ['全屏', '点赞', '投币', '收藏', '按钮'], icon: 'ellipsis.circle', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'showFSLockBtn', label: '全屏显示锁定按钮', keywords: ['锁定', '全屏', '锁'], icon: 'lock', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'showFsScreenshotBtn', label: '全屏显示截图按钮', keywords: ['截图', '全屏', '相机'], icon: 'camera', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'showBatteryLevel', label: '全屏显示电池电量', keywords: ['电池', '电量', '全屏'], icon: 'battery.75', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'superChatType', label: 'SuperChat显示类型', keywords: ['SC', '醒目留言', '直播', 'superchat'], icon: 'text.bubble', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'fullScreenScScale', label: '全屏SC大小', keywords: ['SC', '大小', '缩放', 'superchat'], icon: 'textformat.size', page: '/settings/fullscreen_sc', category: '播放设置', color: '#34C759' },
  { key: 'subtitlePreference', label: '自动启用字幕', keywords: ['字幕', 'CC', 'AI字幕', '自动'], icon: 'captions.bubble', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'subtitleFontScale', label: '字幕字号', keywords: ['字幕', '字号', 'font', 'size', 'scale'], icon: 'textformat.size', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'subtitleFontScaleFS', label: '全屏字幕字号', keywords: ['字幕', '全屏', '字号', 'fullscreen', 'font'], icon: 'textformat.size', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'subtitleFontWeight', label: '字幕粗细', keywords: ['字幕', '粗细', 'font', 'weight', 'bold'], icon: 'bold', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'subtitleStrokeWidth', label: '字幕描边', keywords: ['字幕', '描边', 'stroke', 'outline'], icon: 'scribble', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'subtitlePaddingH', label: '字幕左右边距', keywords: ['字幕', '边距', '左右', 'padding', 'margin'], icon: 'arrow.left.and.right', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'subtitlePaddingB', label: '字幕底部边距', keywords: ['字幕', '边距', '底部', 'padding', 'bottom'], icon: 'arrow.down', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'subtitleBgOpacity', label: '字幕背景透明度', keywords: ['字幕', '背景', '透明度', 'bg', 'opacity'], icon: 'circle.lefthalf.filled', page: '/settings/playback', category: '播放设置', color: '#34C759' },
  { key: 'btmProgressBehavior', label: '底部进度条', keywords: ['进度条', '底部', '显示'], icon: 'minus', page: '/settings/playback', category: '播放设置', color: '#34C759' },

  // ===== 弹幕设置 =====
  { key: 'danmakuEnabled', label: '显示弹幕', keywords: ['弹幕', '开关', '显示'], icon: 'text.bubble', page: '/settings/danmaku', category: '弹幕设置', color: '#AF52DE' },
  { key: 'enableTapDm', label: '启用点击弹幕', keywords: ['弹幕', '点击', '点赞', '复制'], icon: 'hand.point.up.left', page: '/settings/danmaku', category: '弹幕设置', color: '#AF52DE' },
  { key: 'showVipDanmaku', label: '显示会员彩色弹幕', keywords: ['彩色', '会员', '弹幕', '渐变'], icon: 'rainbow', page: '/settings/danmaku', category: '弹幕设置', color: '#AF52DE' },
  { key: 'mergeDanmaku', label: '合并弹幕', keywords: ['合并', '重复', '弹幕'], icon: 'arrow.triangle.merge', page: '/settings/danmaku', category: '弹幕设置', color: '#AF52DE' },
  { key: 'showDmChart', label: '显示高能进度条', keywords: ['高能', '进度条', '弹幕密度'], icon: 'chart.line.uptrend.xyaxis', page: '/settings/danmaku', category: '弹幕设置', color: '#AF52DE' },
  { key: 'danmakuOpacity', label: '弹幕透明度', keywords: ['透明度', '弹幕', '不透明'], icon: 'circle.lefthalf.filled', page: '/settings/danmaku', category: '弹幕设置', color: '#AF52DE' },
  { key: 'danmakuFontSize', label: '弹幕字号', keywords: ['字号', '弹幕', '大小', '字体'], icon: 'textformat', page: '/settings/danmaku', category: '弹幕设置', color: '#AF52DE' },
  { key: 'danmakuSpeed', label: '弹幕速度', keywords: ['速度', '弹幕', '快慢'], icon: 'gauge.with.dots.needle.50percent', page: '/settings/danmaku', category: '弹幕设置', color: '#AF52DE' },
  { key: 'danmakuLineHeight', label: '弹幕行高', keywords: ['行高', '弹幕', '间距'], icon: 'line.3.horizontal', page: '/settings/danmaku', category: '弹幕设置', color: '#AF52DE' },
  { key: 'danmakuColor', label: '弹幕颜色', keywords: ['弹幕', '颜色', '取色', '彩色'], icon: 'paintpalette', page: '/settings/slide_color_picker', category: '弹幕设置', color: '#AF52DE' },
  { key: 'danmakuBlock', label: '弹幕屏蔽管理', keywords: ['屏蔽', '弹幕', '黑名单', '关键词'], icon: 'hand.raised.slash', page: '/danmaku_block', category: '弹幕设置', color: '#AF52DE' },

  // ===== 外观设置 =====
  { key: 'theme', label: '主题模式', keywords: ['深色', '浅色', '暗黑', '主题', '夜间'], icon: 'paintbrush', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'fontSize', label: '字体大小', keywords: ['字号', '字体', '大小', '缩放'], icon: 'textformat.size', page: '/settings/font_size', category: '外观设置', color: '#FF2D55' },
  { key: 'enableDynamicColor', label: '动态取色', keywords: ['取色', '主题色', '颜色', 'accent'], icon: 'wand.and.stars', page: '/settings/color_select', category: '外观设置', color: '#FF2D55' },
  { key: 'accentColor', label: '主题色', keywords: ['主题色', '颜色', 'accent', '强调色'], icon: 'paintpalette', page: '/settings/color_select', category: '外观设置', color: '#FF2D55' },
  { key: 'barSet', label: '首页标签页 / Navbar 排序', keywords: ['标签页', 'navbar', '排序', 'tab', '导航'], icon: 'rectangle.3.group', page: '/settings/bar_set', category: '外观设置', color: '#FF2D55' },
  { key: 'isPureBlackTheme', label: '纯黑主题', keywords: ['纯黑', 'OLED', '深色'], icon: 'moon.fill', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'feedLayout', label: 'Feed布局模式', keywords: ['布局', '单列', '双列', '卡片', '首页'], icon: 'rectangle.grid.1x2', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'picQuality', label: '图片质量', keywords: ['图片', '质量', '清晰度', '流量'], icon: 'photo', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'previewQuality', label: '查看大图质量', keywords: ['大图', '质量', '预览'], icon: 'photo.on.rectangle.angled', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'hideTopBar', label: '首页顶栏收起', keywords: ['顶栏', '收起', '隐藏', '滚动', '搜索栏'], icon: 'chevron.up', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'hideBottomBar', label: '首页底栏收起', keywords: ['底栏', '收起', '隐藏', '滚动', 'tab栏'], icon: 'chevron.down', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'darkVideoPage', label: '视频页深色主题', keywords: ['深色', '视频页', '播放页', '暗黑'], icon: 'moon.circle', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'removeSafeArea', label: '播放页移除安全边距', keywords: ['安全边距', '刘海', '播放页', '全屏'], icon: 'arrow.up.and.down.and.arrow.left.and.right', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'showViewPoints', label: '显示视频分段信息', keywords: ['分段', '章节', '看点'], icon: 'list.number', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'showRelatedVideo', label: '显示相关视频', keywords: ['相关', '推荐', '视频页'], icon: 'square.stack.3d.down.forward', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'showVideoReply', label: '显示视频评论', keywords: ['评论', '显示', '视频'], icon: 'bubble.left.and.text.bubble.right', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'showBangumiReply', label: '显示番剧评论', keywords: ['评论', '番剧', '显示'], icon: 'tv.and.hifispeaker.fill', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'alwaysExpandIntro', label: '默认展开视频简介', keywords: ['简介', '展开', '详情'], icon: 'chevron.down', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'showArgueMsg', label: '显示警告/争议信息', keywords: ['警告', '争议', '提示'], icon: 'exclamationmark.triangle', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'reverseFromFirst', label: '倒序播放从首集开始', keywords: ['倒序', '分P', '合集', '首集'], icon: 'arrow.up.to.line', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'continuePlayingPart', label: '显示继续播放分P提示', keywords: ['续播', '分P', '提示'], icon: 'play.rectangle.on.rectangle', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'enableQuickFav', label: '快速收藏', keywords: ['收藏', '快捷', '默认收藏夹'], icon: 'bookmark', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'defaultShowComment', label: '默认展示评论区', keywords: ['评论', '默认', '展示'], icon: 'text.bubble.fill', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'replyLengthLimit', label: '评论折叠行数', keywords: ['折叠', '评论', '行数'], icon: 'text.line.first.and.arrowtriangle.forward', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'replySortType', label: '评论展示排序', keywords: ['评论', '排序', '热度', '时间'], icon: 'arrow.up.arrow.down', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'enableWordRe', label: '评论区搜索关键词', keywords: ['评论', '搜索', '关键词'], icon: 'magnifyingglass', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'showDecorate', label: '展示头像/评论装饰', keywords: ['装饰', '头像', '挂件'], icon: 'person.crop.circle.badge.checkmark', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'showMedal', label: '显示粉丝勋章', keywords: ['勋章', '粉丝', '徽章'], icon: 'medal', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'checkDynamic', label: '检查未读动态', keywords: ['动态', '未读', '轮询', '红点'], icon: 'bell.badge', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'dynamicBadgeMode', label: '动态未读标记', keywords: ['角标', '红点', '数字', '动态'], icon: 'circlebadge.fill', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'antiGoodsDyn', label: '屏蔽带货动态', keywords: ['带货', '广告', '动态', '屏蔽'], icon: 'cart.badge.minus', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'antiGoodsReply', label: '屏蔽带货评论', keywords: ['带货', '广告', '评论', '屏蔽'], icon: 'cart.badge.minus', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'enableCommAntifraud', label: '发评反诈', keywords: ['反诈', '评论', '可见性', '审核'], icon: 'shield.checkered', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'enableCreateDynAntifraud', label: '发布动态反诈', keywords: ['反诈', '动态', '可见性'], icon: 'shield.lefthalf.filled', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'dynamicsWaterfallFlow', label: '动态页瀑布流', keywords: ['瀑布流', '双列', '动态'], icon: 'square.grid.2x2', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'dynamicsShowAllFollowedUp', label: '显示所有已关注UP', keywords: ['关注', 'UP主', '动态', '列表'], icon: 'person.3', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'expandDynLivePanel', label: '展开正在直播UP列表', keywords: ['直播', 'UP主', '展开'], icon: 'livephoto', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'showDynDispute', label: '显示动态争议信息', keywords: ['争议', '动态', '警告'], icon: 'exclamationmark.bubble', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'showDynActionBar', label: '动态/专栏底部操作栏', keywords: ['操作栏', '底部', '动态', '专栏'], icon: 'ellipsis.rectangle', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'showDynInteraction', label: '显示动态互动内容', keywords: ['互动', '转发', '动态'], icon: 'quote.opening', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'defaultDynamicType', label: '动态展示类型', keywords: ['动态', '类型', '投稿', '番剧'], icon: 'list.bullet.rectangle', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'memberTab', label: '用户页默认TAB', keywords: ['用户', 'UP主', '主页', '默认'], icon: 'sidebar.left', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'showMemberShop', label: '显示UP主页小店TAB', keywords: ['小店', '商店', 'UP主'], icon: 'bag', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'showPgcTimeline', label: '展示追番时间表', keywords: ['追番', '时间表', '番剧', '日历'], icon: 'calendar', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'msgBadgeMode', label: '消息未读标记', keywords: ['消息', '未读', '角标', '红点'], icon: 'bell.badge', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'msgUnReadTypes', label: '消息未读类型', keywords: ['消息', '私信', '回复', '@我', '赞'], icon: 'envelope.badge', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },
  { key: 'defaultHomePage', label: '默认启动页', keywords: ['启动', '首页', '默认', 'tab'], icon: 'house', page: '/settings/appearance', category: '外观设置', color: '#FF2D55' },

  // ===== 其他设置 =====
  { key: 'searchSuggestion', label: '搜索建议', keywords: ['搜索', '联想', '建议'], icon: 'text.magnifyingglass', page: '/settings/extra', category: '其他设置', color: '#8E8E93' },
  { key: 'recordSearchHistory', label: '记录搜索历史', keywords: ['搜索', '历史', '记录'], icon: 'clock.arrow.circlepath', page: '/settings/extra', category: '其他设置', color: '#8E8E93' },
  { key: 'enableHotKey', label: '大家都在搜', keywords: ['热搜', '热门', '搜索'], icon: 'flame', page: '/settings/extra', category: '其他设置', color: '#8E8E93' },
  { key: 'enableSearchRcmd', label: '搜索发现', keywords: ['搜索', '发现', '推荐'], icon: 'safari', page: '/settings/extra', category: '其他设置', color: '#8E8E93' },
  { key: 'enableSearchWord', label: '搜索默认词', keywords: ['搜索', '默认词', '底纹'], icon: 'textformat', page: '/settings/extra', category: '其他设置', color: '#8E8E93' },
  { key: 'feedBackEnable', label: '震动反馈', keywords: ['震动', '触觉', 'haptic', '反馈'], icon: 'iphone.radiowaves.left.and.right', page: '/settings/extra', category: '其他设置', color: '#8E8E93' },
  { key: 'disableLikeMsg', label: '禁用收到的赞', keywords: ['赞', '通知', '消息'], icon: 'hand.thumbsup.slash', page: '/settings/extra', category: '其他设置', color: '#8E8E93' },
  { key: 'openInBrowser', label: '外部浏览器打开链接', keywords: ['浏览器', '外链', 'Safari'], icon: 'arrow.up.right.square', page: '/settings/extra', category: '其他设置', color: '#8E8E93' },
  { key: 'enableAi', label: '启用AI总结', keywords: ['AI', '总结', '摘要', '智能'], icon: 'brain.head.profile', page: '/settings/extra', category: '其他设置', color: '#8E8E93' },
  { key: 'autoUpdate', label: '启动时检查更新', keywords: ['更新', '版本', '升级'], icon: 'arrow.triangle.2.circlepath', page: '/settings/extra', category: '其他设置', color: '#8E8E93' },
  { key: 'enableSponsorBlock', label: '空降助手', keywords: ['sponsor', '跳过', '广告', '空降'], icon: 'shield.checkered', page: '/settings/sponsor_block', category: '其他设置', color: '#8E8E93' },
  { key: 'sponsorBlockCategories', label: '空降助手跳过类别', keywords: ['sponsor', '类别', '跳过', '片头', '片尾'], icon: 'checklist', page: '/settings/sponsor_block', category: '其他设置', color: '#8E8E93' },
  { key: 'sponsorBlockSkipTypes', label: '空降助手跳过策略', keywords: ['sponsor', '策略', '总是跳过', '仅显示'], icon: 'forward.end', page: '/settings/sponsor_block', category: '其他设置', color: '#8E8E93' },
  { key: 'sponsorBlockServer', label: '空降助手服务器', keywords: ['空降', 'sponsor', 'server', '服务端', '服务器', '地址'], icon: 'server.rack', page: '/settings/sponsor_block', category: '其他设置', color: '#8E8E93' },
  { key: 'pgcSkipType', label: '番剧片头/片尾跳过', keywords: ['番剧', '片头', '片尾', '跳过'], icon: 'forward.end', page: '/settings/extra', category: '其他设置', color: '#8E8E93' },
  { key: 'preInitPlayer', label: '提前初始化播放器', keywords: ['预加载', '播放器', '初始化'], icon: 'forward.circle', page: '/settings/extra', category: '其他设置', color: '#8E8E93' },
  { key: 'enableLivePhoto', label: '预览Live Photo', keywords: ['live', 'photo', '动图', '实况'], icon: 'livephoto', page: '/settings/extra', category: '其他设置', color: '#8E8E93' },
  { key: 'saveReply', label: '记录评论', keywords: ['评论', '记录', '草稿'], icon: 'text.quote', page: '/settings/extra', category: '其他设置', color: '#8E8E93' },
  { key: 'silentDownImg', label: '静默下载图片', keywords: ['下载', '图片', '保存', '静默'], icon: 'arrow.down.circle', page: '/settings/extra', category: '其他设置', color: '#8E8E93' },
  { key: 'enableImgMenu', label: '长按显示图片菜单', keywords: ['图片', '菜单', '长按', '保存'], icon: 'menucard', page: '/settings/extra', category: '其他设置', color: '#8E8E93' },
  { key: 'enableDragSubtitle', label: '启用拖拽字幕调整边距', keywords: ['字幕', '拖拽', '边距', '位置'], icon: 'hand.draw', page: '/settings/extra', category: '其他设置', color: '#8E8E93' },
  { key: 'banWordForReply', label: '评论关键词过滤', keywords: ['评论', '屏蔽词', '关键词', '过滤'], icon: 'text.badge.xmark', page: '/settings/extra', category: '其他设置', color: '#8E8E93' },
  { key: 'banWordForDyn', label: '动态关键词过滤', keywords: ['动态', '屏蔽词', '关键词', '过滤'], icon: 'text.badge.xmark', page: '/settings/extra', category: '其他设置', color: '#8E8E93' },
  { key: 'dynamicPeriod', label: '检查未读动态周期', keywords: ['动态', '轮询', '周期', '分钟', '频率'], icon: 'timer.badge.clock', page: '/settings/extra', category: '其他设置', color: '#8E8E93' },
  { key: 'webdav', label: 'WebDAV 设置', keywords: ['WebDAV', '同步', '备份', '网盘'], icon: 'externaldrive', page: '/settings/webdav', category: '其他设置', color: '#8E8E93' },
  { key: 'logs', label: '应用日志', keywords: ['日志', '错误', '崩溃', 'log'], icon: 'doc.text', page: '/settings/logs', category: '其他设置', color: '#8E8E93' },

  // ===== 网络设置 =====
  { key: 'enableHttp2', label: '启用HTTP/2', keywords: ['HTTP2', '协议', '网络'], icon: 'network', page: '/settings/network', category: '网络设置', color: '#5856D6' },
  { key: 'badCertificateCallback', label: '禁用SSL证书验证', keywords: ['SSL', '证书', 'HTTPS', '安全'], icon: 'lock.shield', page: '/settings/network', category: '网络设置', color: '#5856D6' },
  { key: 'retryCount', label: '连接重试次数', keywords: ['重试', '网络', '失败'], icon: 'arrow.triangle.2.circlepath', page: '/settings/network', category: '网络设置', color: '#5856D6' },
  { key: 'retryDelay', label: '连接重试间隔', keywords: ['重试', '间隔', '延迟'], icon: 'hourglass', page: '/settings/network', category: '网络设置', color: '#5856D6' },
  { key: 'enableSystemProxy', label: '启用代理', keywords: ['代理', 'proxy', '抓包'], icon: 'airplane', page: '/settings/network', category: '网络设置', color: '#5856D6' },
  { key: 'systemProxyHost', label: '代理Host', keywords: ['代理', 'host', 'proxy', '服务器', '地址'], icon: 'network', page: '/settings/network', category: '网络设置', color: '#5856D6' },
  { key: 'systemProxyPort', label: '代理Port', keywords: ['代理', 'port', 'proxy', '端口', '号码'], icon: 'number.circle', page: '/settings/network', category: '网络设置', color: '#5856D6' },
  { key: 'maxCacheSize', label: '最大缓存大小', keywords: ['缓存', '大小', '空间', '存储'], icon: 'externaldrive', page: '/settings/network', category: '网络设置', color: '#5856D6' },
  { key: 'clearCache', label: '清除缓存', keywords: ['缓存', '清除', '清理', '空间'], icon: 'trash', page: '/settings/network', category: '网络设置', color: '#5856D6' },

  // ===== 隐私设置 =====
  { key: 'blacklist', label: '黑名单管理', keywords: ['黑名单', '拉黑', '屏蔽', '用户'], icon: 'hand.raised.fill', page: '/blacklist', category: '隐私设置', color: '#FF3B30' },
  { key: 'accountMode', label: '了解账号模式', keywords: ['账号', '模式', 'API', 'web', 'app'], icon: 'info.circle', page: '/settings/privacy', category: '隐私设置', color: '#FF3B30' },
  { key: 'pauseHistory', label: '暂停历史记录', keywords: ['历史', '暂停', '记录', '隐私'], icon: 'pause.circle', page: '/settings/privacy', category: '隐私设置', color: '#FF9500' },
  { key: 'spaceSetting', label: '空间设置', keywords: ['空间', '隐私', '设置', '收藏', '关注'], icon: 'person.crop.circle', page: '/space_setting', category: '隐私设置', color: '#FF3B30' },
];
